// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.github.tjg.myraft.model.proto;

public interface AppendEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.github.tjg.myraft.model.proto.AppendEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 跟随者包含了匹配上 prevLogIndex 和 prevLogTerm 的日志时为真
   * </pre>
   *
   * <code>.org.github.tjg.myraft.model.proto.ResCode res_code = 1;</code>
   * @return The enum numeric value on the wire for resCode.
   */
  int getResCodeValue();
  /**
   * <pre>
   * 跟随者包含了匹配上 prevLogIndex 和 prevLogTerm 的日志时为真
   * </pre>
   *
   * <code>.org.github.tjg.myraft.model.proto.ResCode res_code = 1;</code>
   * @return The resCode.
   */
  org.github.tjg.myraft.model.proto.ResCode getResCode();

  /**
   * <pre>
   * 当前的任期号，用于领导人去更新自己
   * </pre>
   *
   * <code>uint64 term = 2;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>uint64 last_log_index = 3;</code>
   * @return The lastLogIndex.
   */
  long getLastLogIndex();
}
