// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.github.tjg.myraft.model.proto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_LogMetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_LogMetaData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_VoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_VoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_VoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_VoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_Server_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_Server_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_AppendEntriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_AppendEntriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_github_tjg_myraft_model_proto_AppendEntriesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_github_tjg_myraft_model_proto_AppendEntriesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022!org.github.tjg.myraft.mo" +
      "del.proto\"d\n\013LogMetaData\022\024\n\014current_term" +
      "\030\001 \001(\004\022\020\n\010vote_for\030\002 \001(\r\022\027\n\017first_log_in" +
      "dex\030\003 \001(\004\022\024\n\014commit_index\030\004 \001(\004\"]\n\013VoteR" +
      "equest\022\021\n\tserver_id\030\001 \001(\r\022\014\n\004term\030\002 \001(\004\022" +
      "\025\n\rlast_log_term\030\003 \001(\004\022\026\n\016last_log_index" +
      "\030\004 \001(\004\"-\n\014VoteResponse\022\017\n\007granted\030\001 \001(\010\022" +
      "\014\n\004term\030\002 \001(\004\"\206\001\n\020SnapshotMetaData\022\033\n\023la" +
      "st_included_index\030\001 \001(\004\022\032\n\022last_included" +
      "_term\030\002 \001(\004\0229\n\006server\030\003 \003(\0132).org.github" +
      ".tjg.myraft.model.proto.Server\"4\n\006Server" +
      "\022\020\n\010serverId\030\001 \001(\r\022\014\n\004port\030\002 \001(\005\022\n\n\002ip\030\003" +
      " \001(\t\"q\n\010LogEntry\022\014\n\004term\030\001 \001(\004\022\r\n\005index\030" +
      "\002 \001(\004\022:\n\004type\030\003 \001(\0162,.org.github.tjg.myr" +
      "aft.model.proto.EntryType\022\014\n\004data\030\004 \001(\014\"" +
      "\272\001\n\024AppendEntriesRequest\022\021\n\tserver_id\030\001 " +
      "\001(\r\022\014\n\004term\030\002 \001(\004\022\026\n\016prev_log_index\030\003 \001(" +
      "\004\022\025\n\rprev_log_term\030\004 \001(\004\022\024\n\014commit_index" +
      "\030\005 \001(\004\022<\n\007entries\030\006 \001(\0132+.org.github.tjg" +
      ".myraft.model.proto.LogEntry\"{\n\025AppendEn" +
      "triesResponse\022<\n\010res_code\030\001 \001(\0162*.org.gi" +
      "thub.tjg.myraft.model.proto.ResCode\022\014\n\004t" +
      "erm\030\002 \001(\004\022\026\n\016last_log_index\030\003 \001(\004*>\n\tEnt" +
      "ryType\022\023\n\017ENTRY_TYPE_DATA\020\000\022\034\n\030ENTRY_TYP" +
      "E_CONFIGURATION\020\001*K\n\007ResCode\022\024\n\020RES_CODE" +
      "_SUCCESS\020\000\022\021\n\rRES_CODE_FAIL\020\001\022\027\n\023RES_COD" +
      "E_NOT_LEADER\020\002B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_github_tjg_myraft_model_proto_LogMetaData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_github_tjg_myraft_model_proto_LogMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_LogMetaData_descriptor,
        new java.lang.String[] { "CurrentTerm", "VoteFor", "FirstLogIndex", "CommitIndex", });
    internal_static_org_github_tjg_myraft_model_proto_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_github_tjg_myraft_model_proto_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_VoteRequest_descriptor,
        new java.lang.String[] { "ServerId", "Term", "LastLogTerm", "LastLogIndex", });
    internal_static_org_github_tjg_myraft_model_proto_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_github_tjg_myraft_model_proto_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_VoteResponse_descriptor,
        new java.lang.String[] { "Granted", "Term", });
    internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_descriptor,
        new java.lang.String[] { "LastIncludedIndex", "LastIncludedTerm", "Server", });
    internal_static_org_github_tjg_myraft_model_proto_Server_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_github_tjg_myraft_model_proto_Server_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_Server_descriptor,
        new java.lang.String[] { "ServerId", "Port", "Ip", });
    internal_static_org_github_tjg_myraft_model_proto_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_github_tjg_myraft_model_proto_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_LogEntry_descriptor,
        new java.lang.String[] { "Term", "Index", "Type", "Data", });
    internal_static_org_github_tjg_myraft_model_proto_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_github_tjg_myraft_model_proto_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_AppendEntriesRequest_descriptor,
        new java.lang.String[] { "ServerId", "Term", "PrevLogIndex", "PrevLogTerm", "CommitIndex", "Entries", });
    internal_static_org_github_tjg_myraft_model_proto_AppendEntriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_github_tjg_myraft_model_proto_AppendEntriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_github_tjg_myraft_model_proto_AppendEntriesResponse_descriptor,
        new java.lang.String[] { "ResCode", "Term", "LastLogIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
