// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.github.tjg.myraft.model.proto;

/**
 * Protobuf type {@code org.github.tjg.myraft.model.proto.LogMetaData}
 */
public  final class LogMetaData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.github.tjg.myraft.model.proto.LogMetaData)
    LogMetaDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogMetaData.newBuilder() to construct.
  private LogMetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogMetaData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LogMetaData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LogMetaData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            currentTerm_ = input.readUInt64();
            break;
          }
          case 16: {

            voteFor_ = input.readUInt32();
            break;
          }
          case 24: {

            firstLogIndex_ = input.readUInt64();
            break;
          }
          case 32: {

            commitIndex_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_LogMetaData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_LogMetaData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.github.tjg.myraft.model.proto.LogMetaData.class, org.github.tjg.myraft.model.proto.LogMetaData.Builder.class);
  }

  public static final int CURRENT_TERM_FIELD_NUMBER = 1;
  private long currentTerm_;
  /**
   * <code>uint64 current_term = 1;</code>
   * @return The currentTerm.
   */
  public long getCurrentTerm() {
    return currentTerm_;
  }

  public static final int VOTE_FOR_FIELD_NUMBER = 2;
  private int voteFor_;
  /**
   * <code>uint32 vote_for = 2;</code>
   * @return The voteFor.
   */
  public int getVoteFor() {
    return voteFor_;
  }

  public static final int FIRST_LOG_INDEX_FIELD_NUMBER = 3;
  private long firstLogIndex_;
  /**
   * <code>uint64 first_log_index = 3;</code>
   * @return The firstLogIndex.
   */
  public long getFirstLogIndex() {
    return firstLogIndex_;
  }

  public static final int COMMIT_INDEX_FIELD_NUMBER = 4;
  private long commitIndex_;
  /**
   * <code>uint64 commit_index = 4;</code>
   * @return The commitIndex.
   */
  public long getCommitIndex() {
    return commitIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentTerm_ != 0L) {
      output.writeUInt64(1, currentTerm_);
    }
    if (voteFor_ != 0) {
      output.writeUInt32(2, voteFor_);
    }
    if (firstLogIndex_ != 0L) {
      output.writeUInt64(3, firstLogIndex_);
    }
    if (commitIndex_ != 0L) {
      output.writeUInt64(4, commitIndex_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, currentTerm_);
    }
    if (voteFor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, voteFor_);
    }
    if (firstLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, firstLogIndex_);
    }
    if (commitIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, commitIndex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.github.tjg.myraft.model.proto.LogMetaData)) {
      return super.equals(obj);
    }
    org.github.tjg.myraft.model.proto.LogMetaData other = (org.github.tjg.myraft.model.proto.LogMetaData) obj;

    if (getCurrentTerm()
        != other.getCurrentTerm()) return false;
    if (getVoteFor()
        != other.getVoteFor()) return false;
    if (getFirstLogIndex()
        != other.getFirstLogIndex()) return false;
    if (getCommitIndex()
        != other.getCommitIndex()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentTerm());
    hash = (37 * hash) + VOTE_FOR_FIELD_NUMBER;
    hash = (53 * hash) + getVoteFor();
    hash = (37 * hash) + FIRST_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFirstLogIndex());
    hash = (37 * hash) + COMMIT_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommitIndex());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.tjg.myraft.model.proto.LogMetaData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.github.tjg.myraft.model.proto.LogMetaData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.github.tjg.myraft.model.proto.LogMetaData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.github.tjg.myraft.model.proto.LogMetaData)
      org.github.tjg.myraft.model.proto.LogMetaDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_LogMetaData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_LogMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.github.tjg.myraft.model.proto.LogMetaData.class, org.github.tjg.myraft.model.proto.LogMetaData.Builder.class);
    }

    // Construct using org.github.tjg.myraft.model.proto.LogMetaData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentTerm_ = 0L;

      voteFor_ = 0;

      firstLogIndex_ = 0L;

      commitIndex_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_LogMetaData_descriptor;
    }

    @java.lang.Override
    public org.github.tjg.myraft.model.proto.LogMetaData getDefaultInstanceForType() {
      return org.github.tjg.myraft.model.proto.LogMetaData.getDefaultInstance();
    }

    @java.lang.Override
    public org.github.tjg.myraft.model.proto.LogMetaData build() {
      org.github.tjg.myraft.model.proto.LogMetaData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.github.tjg.myraft.model.proto.LogMetaData buildPartial() {
      org.github.tjg.myraft.model.proto.LogMetaData result = new org.github.tjg.myraft.model.proto.LogMetaData(this);
      result.currentTerm_ = currentTerm_;
      result.voteFor_ = voteFor_;
      result.firstLogIndex_ = firstLogIndex_;
      result.commitIndex_ = commitIndex_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.github.tjg.myraft.model.proto.LogMetaData) {
        return mergeFrom((org.github.tjg.myraft.model.proto.LogMetaData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.github.tjg.myraft.model.proto.LogMetaData other) {
      if (other == org.github.tjg.myraft.model.proto.LogMetaData.getDefaultInstance()) return this;
      if (other.getCurrentTerm() != 0L) {
        setCurrentTerm(other.getCurrentTerm());
      }
      if (other.getVoteFor() != 0) {
        setVoteFor(other.getVoteFor());
      }
      if (other.getFirstLogIndex() != 0L) {
        setFirstLogIndex(other.getFirstLogIndex());
      }
      if (other.getCommitIndex() != 0L) {
        setCommitIndex(other.getCommitIndex());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.github.tjg.myraft.model.proto.LogMetaData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.github.tjg.myraft.model.proto.LogMetaData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long currentTerm_ ;
    /**
     * <code>uint64 current_term = 1;</code>
     * @return The currentTerm.
     */
    public long getCurrentTerm() {
      return currentTerm_;
    }
    /**
     * <code>uint64 current_term = 1;</code>
     * @param value The currentTerm to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentTerm(long value) {
      
      currentTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 current_term = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentTerm() {
      
      currentTerm_ = 0L;
      onChanged();
      return this;
    }

    private int voteFor_ ;
    /**
     * <code>uint32 vote_for = 2;</code>
     * @return The voteFor.
     */
    public int getVoteFor() {
      return voteFor_;
    }
    /**
     * <code>uint32 vote_for = 2;</code>
     * @param value The voteFor to set.
     * @return This builder for chaining.
     */
    public Builder setVoteFor(int value) {
      
      voteFor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 vote_for = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVoteFor() {
      
      voteFor_ = 0;
      onChanged();
      return this;
    }

    private long firstLogIndex_ ;
    /**
     * <code>uint64 first_log_index = 3;</code>
     * @return The firstLogIndex.
     */
    public long getFirstLogIndex() {
      return firstLogIndex_;
    }
    /**
     * <code>uint64 first_log_index = 3;</code>
     * @param value The firstLogIndex to set.
     * @return This builder for chaining.
     */
    public Builder setFirstLogIndex(long value) {
      
      firstLogIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 first_log_index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstLogIndex() {
      
      firstLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long commitIndex_ ;
    /**
     * <code>uint64 commit_index = 4;</code>
     * @return The commitIndex.
     */
    public long getCommitIndex() {
      return commitIndex_;
    }
    /**
     * <code>uint64 commit_index = 4;</code>
     * @param value The commitIndex to set.
     * @return This builder for chaining.
     */
    public Builder setCommitIndex(long value) {
      
      commitIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 commit_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitIndex() {
      
      commitIndex_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.github.tjg.myraft.model.proto.LogMetaData)
  }

  // @@protoc_insertion_point(class_scope:org.github.tjg.myraft.model.proto.LogMetaData)
  private static final org.github.tjg.myraft.model.proto.LogMetaData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.github.tjg.myraft.model.proto.LogMetaData();
  }

  public static org.github.tjg.myraft.model.proto.LogMetaData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogMetaData>
      PARSER = new com.google.protobuf.AbstractParser<LogMetaData>() {
    @java.lang.Override
    public LogMetaData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LogMetaData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LogMetaData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogMetaData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.github.tjg.myraft.model.proto.LogMetaData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

