// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.github.tjg.myraft.model.proto;

public interface LogMetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.github.tjg.myraft.model.proto.LogMetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 current_term = 1;</code>
   * @return The currentTerm.
   */
  long getCurrentTerm();

  /**
   * <code>uint32 vote_for = 2;</code>
   * @return The voteFor.
   */
  int getVoteFor();

  /**
   * <code>uint64 first_log_index = 3;</code>
   * @return The firstLogIndex.
   */
  long getFirstLogIndex();

  /**
   * <code>uint64 commit_index = 4;</code>
   * @return The commitIndex.
   */
  long getCommitIndex();
}
