// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.github.tjg.myraft.model.proto;

public interface SnapshotMetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.github.tjg.myraft.model.proto.SnapshotMetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 last_included_index = 1;</code>
   * @return The lastIncludedIndex.
   */
  long getLastIncludedIndex();

  /**
   * <code>uint64 last_included_term = 2;</code>
   * @return The lastIncludedTerm.
   */
  long getLastIncludedTerm();

  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  java.util.List<org.github.tjg.myraft.model.proto.Server> 
      getServerList();
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  org.github.tjg.myraft.model.proto.Server getServer(int index);
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  int getServerCount();
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  java.util.List<? extends org.github.tjg.myraft.model.proto.ServerOrBuilder> 
      getServerOrBuilderList();
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  org.github.tjg.myraft.model.proto.ServerOrBuilder getServerOrBuilder(
      int index);
}
