// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.github.tjg.myraft.model.proto;

/**
 * Protobuf type {@code org.github.tjg.myraft.model.proto.SnapshotMetaData}
 */
public  final class SnapshotMetaData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.github.tjg.myraft.model.proto.SnapshotMetaData)
    SnapshotMetaDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SnapshotMetaData.newBuilder() to construct.
  private SnapshotMetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SnapshotMetaData() {
    server_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SnapshotMetaData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SnapshotMetaData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            lastIncludedIndex_ = input.readUInt64();
            break;
          }
          case 16: {

            lastIncludedTerm_ = input.readUInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              server_ = new java.util.ArrayList<org.github.tjg.myraft.model.proto.Server>();
              mutable_bitField0_ |= 0x00000001;
            }
            server_.add(
                input.readMessage(org.github.tjg.myraft.model.proto.Server.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        server_ = java.util.Collections.unmodifiableList(server_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.github.tjg.myraft.model.proto.SnapshotMetaData.class, org.github.tjg.myraft.model.proto.SnapshotMetaData.Builder.class);
  }

  public static final int LAST_INCLUDED_INDEX_FIELD_NUMBER = 1;
  private long lastIncludedIndex_;
  /**
   * <code>uint64 last_included_index = 1;</code>
   * @return The lastIncludedIndex.
   */
  public long getLastIncludedIndex() {
    return lastIncludedIndex_;
  }

  public static final int LAST_INCLUDED_TERM_FIELD_NUMBER = 2;
  private long lastIncludedTerm_;
  /**
   * <code>uint64 last_included_term = 2;</code>
   * @return The lastIncludedTerm.
   */
  public long getLastIncludedTerm() {
    return lastIncludedTerm_;
  }

  public static final int SERVER_FIELD_NUMBER = 3;
  private java.util.List<org.github.tjg.myraft.model.proto.Server> server_;
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  public java.util.List<org.github.tjg.myraft.model.proto.Server> getServerList() {
    return server_;
  }
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  public java.util.List<? extends org.github.tjg.myraft.model.proto.ServerOrBuilder> 
      getServerOrBuilderList() {
    return server_;
  }
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  public int getServerCount() {
    return server_.size();
  }
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  public org.github.tjg.myraft.model.proto.Server getServer(int index) {
    return server_.get(index);
  }
  /**
   * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
   */
  public org.github.tjg.myraft.model.proto.ServerOrBuilder getServerOrBuilder(
      int index) {
    return server_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lastIncludedIndex_ != 0L) {
      output.writeUInt64(1, lastIncludedIndex_);
    }
    if (lastIncludedTerm_ != 0L) {
      output.writeUInt64(2, lastIncludedTerm_);
    }
    for (int i = 0; i < server_.size(); i++) {
      output.writeMessage(3, server_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lastIncludedIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, lastIncludedIndex_);
    }
    if (lastIncludedTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, lastIncludedTerm_);
    }
    for (int i = 0; i < server_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, server_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.github.tjg.myraft.model.proto.SnapshotMetaData)) {
      return super.equals(obj);
    }
    org.github.tjg.myraft.model.proto.SnapshotMetaData other = (org.github.tjg.myraft.model.proto.SnapshotMetaData) obj;

    if (getLastIncludedIndex()
        != other.getLastIncludedIndex()) return false;
    if (getLastIncludedTerm()
        != other.getLastIncludedTerm()) return false;
    if (!getServerList()
        .equals(other.getServerList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LAST_INCLUDED_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastIncludedIndex());
    hash = (37 * hash) + LAST_INCLUDED_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastIncludedTerm());
    if (getServerCount() > 0) {
      hash = (37 * hash) + SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getServerList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.tjg.myraft.model.proto.SnapshotMetaData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.github.tjg.myraft.model.proto.SnapshotMetaData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.github.tjg.myraft.model.proto.SnapshotMetaData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.github.tjg.myraft.model.proto.SnapshotMetaData)
      org.github.tjg.myraft.model.proto.SnapshotMetaDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.github.tjg.myraft.model.proto.SnapshotMetaData.class, org.github.tjg.myraft.model.proto.SnapshotMetaData.Builder.class);
    }

    // Construct using org.github.tjg.myraft.model.proto.SnapshotMetaData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getServerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lastIncludedIndex_ = 0L;

      lastIncludedTerm_ = 0L;

      if (serverBuilder_ == null) {
        server_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        serverBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.github.tjg.myraft.model.proto.Common.internal_static_org_github_tjg_myraft_model_proto_SnapshotMetaData_descriptor;
    }

    @java.lang.Override
    public org.github.tjg.myraft.model.proto.SnapshotMetaData getDefaultInstanceForType() {
      return org.github.tjg.myraft.model.proto.SnapshotMetaData.getDefaultInstance();
    }

    @java.lang.Override
    public org.github.tjg.myraft.model.proto.SnapshotMetaData build() {
      org.github.tjg.myraft.model.proto.SnapshotMetaData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.github.tjg.myraft.model.proto.SnapshotMetaData buildPartial() {
      org.github.tjg.myraft.model.proto.SnapshotMetaData result = new org.github.tjg.myraft.model.proto.SnapshotMetaData(this);
      int from_bitField0_ = bitField0_;
      result.lastIncludedIndex_ = lastIncludedIndex_;
      result.lastIncludedTerm_ = lastIncludedTerm_;
      if (serverBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          server_ = java.util.Collections.unmodifiableList(server_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.server_ = server_;
      } else {
        result.server_ = serverBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.github.tjg.myraft.model.proto.SnapshotMetaData) {
        return mergeFrom((org.github.tjg.myraft.model.proto.SnapshotMetaData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.github.tjg.myraft.model.proto.SnapshotMetaData other) {
      if (other == org.github.tjg.myraft.model.proto.SnapshotMetaData.getDefaultInstance()) return this;
      if (other.getLastIncludedIndex() != 0L) {
        setLastIncludedIndex(other.getLastIncludedIndex());
      }
      if (other.getLastIncludedTerm() != 0L) {
        setLastIncludedTerm(other.getLastIncludedTerm());
      }
      if (serverBuilder_ == null) {
        if (!other.server_.isEmpty()) {
          if (server_.isEmpty()) {
            server_ = other.server_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServerIsMutable();
            server_.addAll(other.server_);
          }
          onChanged();
        }
      } else {
        if (!other.server_.isEmpty()) {
          if (serverBuilder_.isEmpty()) {
            serverBuilder_.dispose();
            serverBuilder_ = null;
            server_ = other.server_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serverBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServerFieldBuilder() : null;
          } else {
            serverBuilder_.addAllMessages(other.server_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.github.tjg.myraft.model.proto.SnapshotMetaData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.github.tjg.myraft.model.proto.SnapshotMetaData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long lastIncludedIndex_ ;
    /**
     * <code>uint64 last_included_index = 1;</code>
     * @return The lastIncludedIndex.
     */
    public long getLastIncludedIndex() {
      return lastIncludedIndex_;
    }
    /**
     * <code>uint64 last_included_index = 1;</code>
     * @param value The lastIncludedIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLastIncludedIndex(long value) {
      
      lastIncludedIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 last_included_index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastIncludedIndex() {
      
      lastIncludedIndex_ = 0L;
      onChanged();
      return this;
    }

    private long lastIncludedTerm_ ;
    /**
     * <code>uint64 last_included_term = 2;</code>
     * @return The lastIncludedTerm.
     */
    public long getLastIncludedTerm() {
      return lastIncludedTerm_;
    }
    /**
     * <code>uint64 last_included_term = 2;</code>
     * @param value The lastIncludedTerm to set.
     * @return This builder for chaining.
     */
    public Builder setLastIncludedTerm(long value) {
      
      lastIncludedTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 last_included_term = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastIncludedTerm() {
      
      lastIncludedTerm_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.github.tjg.myraft.model.proto.Server> server_ =
      java.util.Collections.emptyList();
    private void ensureServerIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        server_ = new java.util.ArrayList<org.github.tjg.myraft.model.proto.Server>(server_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.github.tjg.myraft.model.proto.Server, org.github.tjg.myraft.model.proto.Server.Builder, org.github.tjg.myraft.model.proto.ServerOrBuilder> serverBuilder_;

    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public java.util.List<org.github.tjg.myraft.model.proto.Server> getServerList() {
      if (serverBuilder_ == null) {
        return java.util.Collections.unmodifiableList(server_);
      } else {
        return serverBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public int getServerCount() {
      if (serverBuilder_ == null) {
        return server_.size();
      } else {
        return serverBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public org.github.tjg.myraft.model.proto.Server getServer(int index) {
      if (serverBuilder_ == null) {
        return server_.get(index);
      } else {
        return serverBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder setServer(
        int index, org.github.tjg.myraft.model.proto.Server value) {
      if (serverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServerIsMutable();
        server_.set(index, value);
        onChanged();
      } else {
        serverBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder setServer(
        int index, org.github.tjg.myraft.model.proto.Server.Builder builderForValue) {
      if (serverBuilder_ == null) {
        ensureServerIsMutable();
        server_.set(index, builderForValue.build());
        onChanged();
      } else {
        serverBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder addServer(org.github.tjg.myraft.model.proto.Server value) {
      if (serverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServerIsMutable();
        server_.add(value);
        onChanged();
      } else {
        serverBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder addServer(
        int index, org.github.tjg.myraft.model.proto.Server value) {
      if (serverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServerIsMutable();
        server_.add(index, value);
        onChanged();
      } else {
        serverBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder addServer(
        org.github.tjg.myraft.model.proto.Server.Builder builderForValue) {
      if (serverBuilder_ == null) {
        ensureServerIsMutable();
        server_.add(builderForValue.build());
        onChanged();
      } else {
        serverBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder addServer(
        int index, org.github.tjg.myraft.model.proto.Server.Builder builderForValue) {
      if (serverBuilder_ == null) {
        ensureServerIsMutable();
        server_.add(index, builderForValue.build());
        onChanged();
      } else {
        serverBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder addAllServer(
        java.lang.Iterable<? extends org.github.tjg.myraft.model.proto.Server> values) {
      if (serverBuilder_ == null) {
        ensureServerIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, server_);
        onChanged();
      } else {
        serverBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder clearServer() {
      if (serverBuilder_ == null) {
        server_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serverBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public Builder removeServer(int index) {
      if (serverBuilder_ == null) {
        ensureServerIsMutable();
        server_.remove(index);
        onChanged();
      } else {
        serverBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public org.github.tjg.myraft.model.proto.Server.Builder getServerBuilder(
        int index) {
      return getServerFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public org.github.tjg.myraft.model.proto.ServerOrBuilder getServerOrBuilder(
        int index) {
      if (serverBuilder_ == null) {
        return server_.get(index);  } else {
        return serverBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public java.util.List<? extends org.github.tjg.myraft.model.proto.ServerOrBuilder> 
         getServerOrBuilderList() {
      if (serverBuilder_ != null) {
        return serverBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(server_);
      }
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public org.github.tjg.myraft.model.proto.Server.Builder addServerBuilder() {
      return getServerFieldBuilder().addBuilder(
          org.github.tjg.myraft.model.proto.Server.getDefaultInstance());
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public org.github.tjg.myraft.model.proto.Server.Builder addServerBuilder(
        int index) {
      return getServerFieldBuilder().addBuilder(
          index, org.github.tjg.myraft.model.proto.Server.getDefaultInstance());
    }
    /**
     * <code>repeated .org.github.tjg.myraft.model.proto.Server server = 3;</code>
     */
    public java.util.List<org.github.tjg.myraft.model.proto.Server.Builder> 
         getServerBuilderList() {
      return getServerFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.github.tjg.myraft.model.proto.Server, org.github.tjg.myraft.model.proto.Server.Builder, org.github.tjg.myraft.model.proto.ServerOrBuilder> 
        getServerFieldBuilder() {
      if (serverBuilder_ == null) {
        serverBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.github.tjg.myraft.model.proto.Server, org.github.tjg.myraft.model.proto.Server.Builder, org.github.tjg.myraft.model.proto.ServerOrBuilder>(
                server_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        server_ = null;
      }
      return serverBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.github.tjg.myraft.model.proto.SnapshotMetaData)
  }

  // @@protoc_insertion_point(class_scope:org.github.tjg.myraft.model.proto.SnapshotMetaData)
  private static final org.github.tjg.myraft.model.proto.SnapshotMetaData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.github.tjg.myraft.model.proto.SnapshotMetaData();
  }

  public static org.github.tjg.myraft.model.proto.SnapshotMetaData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SnapshotMetaData>
      PARSER = new com.google.protobuf.AbstractParser<SnapshotMetaData>() {
    @java.lang.Override
    public SnapshotMetaData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SnapshotMetaData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SnapshotMetaData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SnapshotMetaData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.github.tjg.myraft.model.proto.SnapshotMetaData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

