// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.github.tjg.myraft.model.proto;

public interface VoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.github.tjg.myraft.model.proto.VoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求选票的候选人的 Id
   * </pre>
   *
   * <code>uint32 server_id = 1;</code>
   * @return The serverId.
   */
  int getServerId();

  /**
   * <pre>
   * 候选人的任期号
   * </pre>
   *
   * <code>uint64 term = 2;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <pre>
   * 候选人的最后日志条目的任期号
   * </pre>
   *
   * <code>uint64 last_log_term = 3;</code>
   * @return The lastLogTerm.
   */
  long getLastLogTerm();

  /**
   * <pre>
   * 候选人最后日志条目的索引值
   * </pre>
   *
   * <code>uint64 last_log_index = 4;</code>
   * @return The lastLogIndex.
   */
  long getLastLogIndex();
}
